package com.supermarket.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGIdIsNull() {
            addCriterion("g_id is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("g_id is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(Integer value) {
            addCriterion("g_id =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(Integer value) {
            addCriterion("g_id <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(Integer value) {
            addCriterion("g_id >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("g_id >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(Integer value) {
            addCriterion("g_id <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(Integer value) {
            addCriterion("g_id <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<Integer> values) {
            addCriterion("g_id in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<Integer> values) {
            addCriterion("g_id not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(Integer value1, Integer value2) {
            addCriterion("g_id between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(Integer value1, Integer value2) {
            addCriterion("g_id not between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGNameIsNull() {
            addCriterion("g_name is null");
            return (Criteria) this;
        }

        public Criteria andGNameIsNotNull() {
            addCriterion("g_name is not null");
            return (Criteria) this;
        }

        public Criteria andGNameEqualTo(String value) {
            addCriterion("g_name =", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotEqualTo(String value) {
            addCriterion("g_name <>", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThan(String value) {
            addCriterion("g_name >", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThanOrEqualTo(String value) {
            addCriterion("g_name >=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThan(String value) {
            addCriterion("g_name <", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThanOrEqualTo(String value) {
            addCriterion("g_name <=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLike(String value) {
            addCriterion("g_name like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotLike(String value) {
            addCriterion("g_name not like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameIn(List<String> values) {
            addCriterion("g_name in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotIn(List<String> values) {
            addCriterion("g_name not in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameBetween(String value1, String value2) {
            addCriterion("g_name between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotBetween(String value1, String value2) {
            addCriterion("g_name not between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGPriceIsNull() {
            addCriterion("g_price is null");
            return (Criteria) this;
        }

        public Criteria andGPriceIsNotNull() {
            addCriterion("g_price is not null");
            return (Criteria) this;
        }

        public Criteria andGPriceEqualTo(Double value) {
            addCriterion("g_price =", value, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceNotEqualTo(Double value) {
            addCriterion("g_price <>", value, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceGreaterThan(Double value) {
            addCriterion("g_price >", value, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("g_price >=", value, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceLessThan(Double value) {
            addCriterion("g_price <", value, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceLessThanOrEqualTo(Double value) {
            addCriterion("g_price <=", value, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceIn(List<Double> values) {
            addCriterion("g_price in", values, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceNotIn(List<Double> values) {
            addCriterion("g_price not in", values, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceBetween(Double value1, Double value2) {
            addCriterion("g_price between", value1, value2, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGPriceNotBetween(Double value1, Double value2) {
            addCriterion("g_price not between", value1, value2, "gPrice");
            return (Criteria) this;
        }

        public Criteria andGCountIsNull() {
            addCriterion("g_count is null");
            return (Criteria) this;
        }

        public Criteria andGCountIsNotNull() {
            addCriterion("g_count is not null");
            return (Criteria) this;
        }

        public Criteria andGCountEqualTo(String value) {
            addCriterion("g_count =", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountNotEqualTo(String value) {
            addCriterion("g_count <>", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountGreaterThan(String value) {
            addCriterion("g_count >", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountGreaterThanOrEqualTo(String value) {
            addCriterion("g_count >=", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountLessThan(String value) {
            addCriterion("g_count <", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountLessThanOrEqualTo(String value) {
            addCriterion("g_count <=", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountLike(String value) {
            addCriterion("g_count like", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountNotLike(String value) {
            addCriterion("g_count not like", value, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountIn(List<String> values) {
            addCriterion("g_count in", values, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountNotIn(List<String> values) {
            addCriterion("g_count not in", values, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountBetween(String value1, String value2) {
            addCriterion("g_count between", value1, value2, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCountNotBetween(String value1, String value2) {
            addCriterion("g_count not between", value1, value2, "gCount");
            return (Criteria) this;
        }

        public Criteria andGCreattimeIsNull() {
            addCriterion("g_creattime is null");
            return (Criteria) this;
        }

        public Criteria andGCreattimeIsNotNull() {
            addCriterion("g_creattime is not null");
            return (Criteria) this;
        }

        public Criteria andGCreattimeEqualTo(Date value) {
            addCriterion("g_creattime =", value, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeNotEqualTo(Date value) {
            addCriterion("g_creattime <>", value, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeGreaterThan(Date value) {
            addCriterion("g_creattime >", value, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeGreaterThanOrEqualTo(Date value) {
            addCriterion("g_creattime >=", value, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeLessThan(Date value) {
            addCriterion("g_creattime <", value, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeLessThanOrEqualTo(Date value) {
            addCriterion("g_creattime <=", value, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeIn(List<Date> values) {
            addCriterion("g_creattime in", values, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeNotIn(List<Date> values) {
            addCriterion("g_creattime not in", values, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeBetween(Date value1, Date value2) {
            addCriterion("g_creattime between", value1, value2, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGCreattimeNotBetween(Date value1, Date value2) {
            addCriterion("g_creattime not between", value1, value2, "gCreattime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeIsNull() {
            addCriterion("g_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeIsNotNull() {
            addCriterion("g_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeEqualTo(Date value) {
            addCriterion("g_updatetime =", value, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeNotEqualTo(Date value) {
            addCriterion("g_updatetime <>", value, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeGreaterThan(Date value) {
            addCriterion("g_updatetime >", value, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("g_updatetime >=", value, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeLessThan(Date value) {
            addCriterion("g_updatetime <", value, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("g_updatetime <=", value, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeIn(List<Date> values) {
            addCriterion("g_updatetime in", values, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeNotIn(List<Date> values) {
            addCriterion("g_updatetime not in", values, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("g_updatetime between", value1, value2, "gUpdatetime");
            return (Criteria) this;
        }

        public Criteria andGUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("g_updatetime not between", value1, value2, "gUpdatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated do_not_delete_during_merge Sat May 14 14:39:42 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated Sat May 14 14:39:42 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}